service: elysia-prisma-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /users
          method: get
      - http:
          path: /users
          method: post

plugins:
  - serverless-offline
